name: union_bank_mobile
description: Union Bank UBGO.


version: 1.0.167+103

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6

  # Firebase
  firebase_core: ^3.2.0
  firebase_messaging: ^15.0.3
  device_info_plus: ^9.1.2
  page_transition: ^2.1.0
  flutter_local_notifications: ^17.2.2
  google_fonts: ^6.1.0
  shared_preferences: ^2.2.2
  connectivity_plus: ^6.0.5
  hex: ^0.2.0
  get_it: ^7.6.7
  package_info_plus: ^8.0.0
  equatable: ^2.0.5
  installer_info: ^0.5.0
  flutter_bloc: ^8.1.4
  intl: ^0.19.0
  flutter_localization: ^0.2.0
  flutter_riverpod: ^2.4.10
  url_launcher: ^6.2.5
  carousel_slider: ^5.0.0
  flutter_secure_storage: ^9.2.2
  flutter_svg: ^2.0.9
  flutter_masked_text2: ^0.9.1
  simple_animations: ^5.0.2
  super_tooltip: ^2.0.7
  pin_code_fields: ^8.0.1
  image_picker: ^1.0.7
  file_picker: ^8.0.0+1
  local_auth: ^2.3.0
  flutter_screenutil: ^5.9.3
  image_cropper: ^5.0.1
  dotted_border: ^2.1.0
  uuid: ^4.3.3
  flutter_udid: ^3.0.0
  geolocator: ^11.0.0
  fpdart: ^1.1.0
  permission_handler: ^11.3.1
  bloc: ^8.1.4
  timeago: ^3.6.1
  open_filex: ^4.5.0
  share_plus: ^7.2.2
  cached_network_image: ^3.3.1
  flutter_html: ^3.0.0-alpha.6
  google_maps_flutter: ^2.9.0
  webfeed_plus: 1.0.1+1
  liquid_pull_to_refresh: ^3.0.1
  path_provider: ^2.1.2
  reorderable_grid: ^1.0.10
  # persistent_bottom_nav_bar: ^5.0.2
  jiffy: ^6.3.0

  #QR code scanner
  qr_code_scanner: ^1.0.1

  flutter_inappwebview: ^5.8.0
  double_back_to_close_app: ^2.1.0
  intl_phone_field: ^3.2.0
  mask_text_input_formatter: ^2.9.0
  
  #Huawei Packages
  huawei_location: ^6.12.0+301
  huawei_map: ^6.11.2+301
  huawei_push: ^6.12.0+302

  #Dio Packages
  dio: ^5.4.1
  dio_http2_adapter: ^2.5.0


  flutter_contacts: ^1.1.7+1
  scrollable_positioned_list: ^0.3.8

  #Sentry For Api Performence
  # sentry_flutter: ^7.18.0
  # sentry_dio: ^7.18.0

  #ENV
  # envied: ^0.5.3

  #Complience
  # freerasp: ^6.4.0

  #Encryption
  basic_utils: ^5.7.0
  pointycastle: ^3.7.4

  #PhosperIcons
  phosphor_flutter: ^2.1.0

  # alphabet_list_view: ^1.1.0

  lottie: ^3.1.2

  app_links: ^6.1.3


  #Analytics
#  huawei_analytics: ^6.12.0+301
#  agconnect_crash: ^1.9.0+300
  firebase_analytics: ^11.2.0
  firebase_crashlytics: ^4.0.3

  app_settings: ^5.1.1
  characters: ^1.3.0
  


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.13.1
  envied_generator: ^0.5.3
  build_runner: ^2.4.8

dependency_overrides:
  intl: ^0.18.1

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/png_new/appiconios.png"
  adaptive_icon_foreground: "assets/png_new/appicon.png"
  image_path_ios: "assets/png_new/appiconios.png"
  adaptive_icon_background:  "#ffffff"

  flutter_lints: ^3.0.0
  change_app_package_name: ^1.1.0



flutter:

  uses-material-design: true
  assets:
    - locales/
    - assets/webp/
    - assets/svg_new/
    - assets/png_new/
    - assets/png_new/banks/
    - assets/animations/
  fonts:
    - family: Proxima
      fonts:
        - asset: fonts/ProximaNova-Bold.otf
          weight: 700
        - asset: fonts/ProximaNova-Regular.otf
          weight: 400
